### ISSUE TITLE
请问这几个项目有什么作用？

### ISSUE THREAD

**Issue by kajweb** [Beven91/freedom#1]
webpack-wxapp-module-plugin，不太懂。

**Comment by Beven91** [comment]
你好，
因为工程的目标是`使用webpack来打包构建微信小程序` 
由于小程序的页面模块分为 `.js` `.wxml` `.wxss`以及`.json`等文件，
webpack默认是根据入口文件来搜索依赖，然而小程序页面模块是`约定依赖`，
所以使用`webpack-wxapp-module-plugin` 来根据`app.json` 来加载`约定依赖`(例如:用到的`page`,`component`,以及`subPackages`以及每个模块对应的文件) 用于 `webpack` 打包使用,
从而可以使用相关loader处理`.wxml` `.wxss` 等。
